# Generated by Django 3.1.5 on 2021-04-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
    ]
