# Generated by Django 3.1.5 on 2021-04-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210406_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
