# Generated by Django 3.1.5 on 2021-04-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
