# Generated by Django 3.1.5 on 2021-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
