# Generated by Django 3.1.5 on 2021-04-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210420_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
