# Generated by Django 3.1.5 on 2021-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
