# Generated by Django 3.1.5 on 2021-04-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210420_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='inventory',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
