# Generated by Django 3.1.5 on 2021-04-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20210421_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
