# Generated by Django 3.1.5 on 2021-04-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20210423_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
